PL/SQL Developer Test script 3.0
257

declare 

begin

      inserts.Country('CR','Costa Rica');
      inserts.Country('CL','Chile');
      inserts.Country('CN','China');
     inserts.Country('EC','Ecuador');
     inserts.Country('AF','Afghanistan');
     inserts.Country('AX','Aland Islands');
     inserts.Country('AL','Albania');
     inserts.Country('DZ','Algeria');
     inserts.Country('AS','American Samoa');
     inserts.Country('AD','Andorra');
     inserts.Country('AO','Angola');
     inserts.Country('AI','Anguilla');
     inserts.Country('AQ','Antarctica');
     inserts.Country('AG','Antigua and Barbuda');
     inserts.Country('AR','Argentina');
     inserts.Country('AM','Armenia');
     inserts.Country('AW','Aruba');
     inserts.Country('AU','Australia');
     inserts.Country('AT','Austria');
     inserts.Country('AZ','Azerbaijan');
     inserts.Country('BS','Bahamas');
     inserts.Country('BH','Bahrain');
     inserts.Country('BD','Bangladesh');
     inserts.Country('BB','Barbados');
     inserts.Country('BY','Belarus');
     inserts.Country('BE','Belgium');
     inserts.Country('BZ','Belize');
     inserts.Country('BJ','Benin');
     inserts.Country('BM','Bermuda');
     inserts.Country('BT','Bhutan');
     inserts.Country('BO','Bolivia, Plurinational State of');
     inserts.Country('BQ','Bonaire, Sint Eustatius and Saba');
     inserts.Country('BA','Bosnia and Herzegovina');
     inserts.Country('BW','Botswana');
     inserts.Country('BV','Bouvet Island');
     inserts.Country('BR','Brazil');
     inserts.Country('IO','British Indian Ocean Territory');
     inserts.Country('BN','Brunei Darussalam');
     inserts.Country('BG','Bulgaria');
     inserts.Country('BF','Burkina Faso');
     inserts.Country('BI','Burundi');
     inserts.Country('KH','Cambodia');
     inserts.Country('CM','Cameroon');
     inserts.Country('CA','Canada');
     inserts.Country('CV','Cape Verde');
     inserts.Country('KY','Cayman Islands');
     inserts.Country('CF','Central African Republic');
     inserts.Country('TD','Chad');
     inserts.Country('CX','Christmas Island');
     inserts.Country('CC','Cocos (Keeling) Islands');
     inserts.Country('CO','Colombia');
     inserts.Country('KM','Comoros');
     inserts.Country('CG','Congo');
     inserts.Country('CD','Congo the Democratic Republic of the');
     inserts.Country('CK','Cook Islands');
     inserts.Country('CI','Côte d_Ivoire');
     inserts.Country('HR','Croatia');
     inserts.Country('CU','Cuba');
     inserts.Country('CW','Curaçao');
     inserts.Country('CY','Cyprus');
     inserts.Country('CZ','Czech Republic');
     inserts.Country('DK','Denmark');
     inserts.Country('DJ','Djibouti');
     inserts.Country('DM','Dominica');
     inserts.Country('DO','Dominican Republic');
     inserts.Country('EG','Egypt');
     inserts.Country('SV','El Salvador');
     inserts.Country('GQ','Equatorial Guinea');
     inserts.Country('ER','Eritrea');
     inserts.Country('EE','Estonia');
     inserts.Country('ET','Ethiopia');
     inserts.Country('FK','Falkland Islands (Malvinas)');
     inserts.Country('FO','Faroe Islands');
     inserts.Country('FJ','Fiji');
     inserts.Country('FI','Finland');
     inserts.Country('FR','France');
     inserts.Country('GF','French Guiana');
     inserts.Country('PF','French Polynesia');
     inserts.Country('TF','French Southern Territories');
     inserts.Country('GA','Gabon');
     inserts.Country('GM','Gambia');
     inserts.Country('GE','Georgia');
     inserts.Country('DE','Germany');
     inserts.Country('GH','Ghana');
     inserts.Country('GI','Gibraltar');
     inserts.Country('GR','Greece');
     inserts.Country('GL','Greenland');
     inserts.Country('GD','Grenada');
     inserts.Country('GP','Guadeloupe');
     inserts.Country('GU','Guam');
     inserts.Country('GT','Guatemala');
     inserts.Country('GG','Guernsey');
     inserts.Country('GN','Guinea');
     inserts.Country('GW','Guinea-Bissau');
     inserts.Country('GY','Guyana');
     inserts.Country('HT','Haiti');
     inserts.Country('HM','Heard Island_and McDonald Islands');
     inserts.Country('VA','Holy See (Vatican City State)');
     inserts.Country('HN','Honduras');
     inserts.Country('HK','Hong Kong');
     inserts.Country('HU','Hungary');
     inserts.Country('IS','Iceland');
     inserts.Country('IN','India');
     inserts.Country('ID','Indonesia');
     inserts.Country('IR','Iran Islamic Republic ');
     inserts.Country('IQ','Iraq');
     inserts.Country('IE','Ireland');
     inserts.Country('IM','Isle Man');
     inserts.Country('IL','Israel');
     inserts.Country('IT','Italy');
     inserts.Country('JM','Jamaica');
     inserts.Country('JP','Japan');
     inserts.Country('JE','Jersey');
     inserts.Country('JO','Jordan');
     inserts.Country('KZ','Kazakhstan');
     inserts.Country('KE','Kenya');
     inserts.Country('KI','Kiribati');
     inserts.Country('KP','Korea Democratic Peoples Republic');
     inserts.Country('KR','Korea Republic');
     inserts.Country('KW','Kuwait');
     inserts.Country('KG','Kyrgyzstan');
     inserts.Country('LA','Lao Peoples Democratic Republic');
     inserts.Country('LV','Latvia');
     inserts.Country('LB','Lebanon');
     inserts.Country('LS','Lesotho');
     inserts.Country('LR','Liberia');
     inserts.Country('LY','Libya');
     inserts.Country('LI','Liechtenstein');
     inserts.Country('LT','Lithuania');
     inserts.Country('LU','Luxembourg');
     inserts.Country('MO','Macao');
     inserts.Country('MK','Macedonia former Yugoslav Republic');
     inserts.Country('MG','Madagascar');
     inserts.Country('MW','Malawi');
     inserts.Country('MY','Malaysia');
     inserts.Country('MV','Maldives');
     inserts.Country('ML','Mali');
     inserts.Country('MT','Malta');
     inserts.Country('MH','Marshall Islands');
     inserts.Country('MQ','Martinique');
     inserts.Country('MR','Mauritania');
     inserts.Country('MU','Mauritius');
     inserts.Country('YT','Mayotte');
     inserts.Country('MX','Mexico');
     inserts.Country('FM','Micronesia Federated States');
     inserts.Country('MD','Moldova Republic');
     inserts.Country('MC','Monaco');
     inserts.Country('MN','Mongolia');
     inserts.Country('ME','Montenegro');
     inserts.Country('MS','Montserrat');
     inserts.Country('MA','Morocco');
     inserts.Country('MZ','Mozambique');
     inserts.Country('MM','Myanmar');
     inserts.Country('NA','Namibia');
     inserts.Country('NR','Nauru');
     inserts.Country('NP','Nepal');
     inserts.Country('NL','Netherlands');
     inserts.Country('NC','New_Caledonia');
     inserts.Country('NZ','New_Zealand');
     inserts.Country('NI','Nicaragua');
     inserts.Country('NE','Niger');
     inserts.Country('NG','Nigeria');
     inserts.Country('NU','Niue');
     inserts.Country('NF','Norfolk Island');
     inserts.Country('MP','Northern Mariana Islands');
     inserts.Country('NO','Norway');
     inserts.Country('OM','Oman');
     inserts.Country('PK','Pakistan');
     inserts.Country('PW','Palau');
     inserts.Country('PS','Palestinian Territory, Occupied');
     inserts.Country('PA','Panama');
     inserts.Country('PG','Papua Nueva Guinea');
     inserts.Country('PY','Paraguay');
     inserts.Country('PE','Peru');
     inserts.Country('PH','Philippines');
     inserts.Country('PN','Pitcairn');
     inserts.Country('PL','Poland');
     inserts.Country('PT','Portugal');
     inserts.Country('PR','Puerto Rico');
     inserts.Country('QA','Qatar');
     inserts.Country('RE','Réunion');
     inserts.Country('RO','Romania');
     inserts.Country('RU','Russian Federation');
     inserts.Country('RW','Rwanda');
     inserts.Country('BL','Saint Barthélemy');
     inserts.Country('SH','Saint Helena, Ascension_and Tristan da Cunha');
     inserts.Country('KN','Saint Kitts_and Nevis');
     inserts.Country('LC','Saint Lucia');
     inserts.Country('MF','Saint Martin (French part)');
     inserts.Country('PM','Saint Pierre_and Miquelon');
     inserts.Country('VC','Saint Vincent_and_the Grenadines');
     inserts.Country('WS','Samoa');
     inserts.Country('SM','San Marino');
     inserts.Country('ST','Sao Tome_and Principe');
     inserts.Country('SA','Saudi Arabia');
     inserts.Country('SN','Senegal');
     inserts.Country('RS','Serbia');
     inserts.Country('SC','Seychelles');
     inserts.Country('SL','Sierra Leone');
     inserts.Country('SG','Singapore');
     inserts.Country('SX','Sint Maarten (Dutch part)');
     inserts.Country('SK','Slovakia');
     inserts.Country('SI','Slovenia');
     inserts.Country('SB','Solomon Islands');
     inserts.Country('SO','Somalia');
     inserts.Country('ZA','South Africa');
     inserts.Country('GS','South Georgia_and the_South Sandwich Islands');
     inserts.Country('SS','South Sudan');
     inserts.Country('ES','Spain');
     inserts.Country('LK','Sri Lanka');
     inserts.Country('SD','Sudan');
     inserts.Country('SR','Suriname');
     inserts.Country('SJ','Svalbard_and Jan Mayen');
     inserts.Country('SZ','Swaziland');
     inserts.Country('SE','Sweden');
     inserts.Country('CH','Switzerland');
     inserts.Country('SY','Syrian Arab Republic');
     inserts.Country('TW','Taiwan, Province_of China');
     inserts.Country('TJ','Tajikistan');
     inserts.Country('TZ','Tanzania, United Republic_of');
     inserts.Country('TH','Thailand');
     inserts.Country('TL','Timor-Leste');
     inserts.Country('TG','Togo');
     inserts.Country('TK','Tokelau');
     inserts.Country('TO','Tonga');
     inserts.Country('TT','Trinidad_and Tobago');
     inserts.Country('TN','Tunisia');
     inserts.Country('TR','Turkey');
     inserts.Country('TM','Turkmenistan');
     inserts.Country('TC','Turks_and Caicos Islands');
     inserts.Country('TV','Tuvalu');
     inserts.Country('UG','Uganda');
     inserts.Country('UA','Ukraine');
     inserts.Country('AE','United Arab Emirates');
     inserts.Country('GB','United Kingdom');
     inserts.Country('US','United States');
     inserts.Country('UM','United States Minor Outlying Islands');
     inserts.Country('UY','Uruguay');
     inserts.Country('UZ','Uzbekistan');
     inserts.Country('VU','Vanuatu');
     inserts.Country('VE','Venezuela Bolivarian Republic_of');
     inserts.Country('VN','Viet Nam');
     inserts.Country('VG','Virgin Islands, British');
     inserts.Country('VI','Virgin Islands, U.S.');
     inserts.Country('WF','Wallis_and Futuna');
     inserts.Country('EH','Western Sahara');
     inserts.Country('YE','Yemen');
     inserts.Country('ZM','Zambia');
     inserts.Country('ZW','Zimbabwe');
                

end;
0
0
