PL/SQL Developer Test script 3.0
257

declare 

begin

      insertCountry('CR','Costa Rica');
      insertCountry('CL','Chile');
      insertCountry('CN','China');
     insertCountry('EC','Ecuador');
     insertCountry('AF','Afghanistan');
     insertCountry('AX','Aland Islands');
     insertCountry('AL','Albania');
     insertCountry('DZ','Algeria');
     insertCountry('AS','American Samoa');
     insertCountry('AD','Andorra');
     insertCountry('AO','Angola');
     insertCountry('AI','Anguilla');
     insertCountry('AQ','Antarctica');
     insertCountry('AG','Antigua and Barbuda');
     insertCountry('AR','Argentina');
     insertCountry('AM','Armenia');
     insertCountry('AW','Aruba');
     insertCountry('AU','Australia');
     insertCountry('AT','Austria');
     insertCountry('AZ','Azerbaijan');
     insertCountry('BS','Bahamas');
     insertCountry('BH','Bahrain');
     insertCountry('BD','Bangladesh');
     insertCountry('BB','Barbados');
     insertCountry('BY','Belarus');
     insertCountry('BE','Belgium');
     insertCountry('BZ','Belize');
     insertCountry('BJ','Benin');
     insertCountry('BM','Bermuda');
     insertCountry('BT','Bhutan');
     insertCountry('BO','Bolivia, Plurinational State of');
     insertCountry('BQ','Bonaire, Sint Eustatius and Saba');
     insertCountry('BA','Bosnia and Herzegovina');
     insertCountry('BW','Botswana');
     insertCountry('BV','Bouvet Island');
     insertCountry('BR','Brazil');
     insertCountry('IO','British Indian Ocean Territory');
     insertCountry('BN','Brunei Darussalam');
     insertCountry('BG','Bulgaria');
     insertCountry('BF','Burkina Faso');
     insertCountry('BI','Burundi');
     insertCountry('KH','Cambodia');
     insertCountry('CM','Cameroon');
     insertCountry('CA','Canada');
     insertCountry('CV','Cape Verde');
     insertCountry('KY','Cayman Islands');
     insertCountry('CF','Central African Republic');
     insertCountry('TD','Chad');
     insertCountry('CX','Christmas Island');
     insertCountry('CC','Cocos (Keeling) Islands');
     insertCountry('CO','Colombia');
     insertCountry('KM','Comoros');
     insertCountry('CG','Congo');
     insertCountry('CD','Congo the Democratic Republic of the');
     insertCountry('CK','Cook Islands');
     insertCountry('CI','Côte d_Ivoire');
     insertCountry('HR','Croatia');
     insertCountry('CU','Cuba');
     insertCountry('CW','Curaçao');
     insertCountry('CY','Cyprus');
     insertCountry('CZ','Czech Republic');
     insertCountry('DK','Denmark');
     insertCountry('DJ','Djibouti');
     insertCountry('DM','Dominica');
     insertCountry('DO','Dominican Republic');
     insertCountry('EG','Egypt');
     insertCountry('SV','El Salvador');
     insertCountry('GQ','Equatorial Guinea');
     insertCountry('ER','Eritrea');
     insertCountry('EE','Estonia');
     insertCountry('ET','Ethiopia');
     insertCountry('FK','Falkland Islands (Malvinas)');
     insertCountry('FO','Faroe Islands');
     insertCountry('FJ','Fiji');
     insertCountry('FI','Finland');
     insertCountry('FR','France');
     insertCountry('GF','French Guiana');
     insertCountry('PF','French Polynesia');
     insertCountry('TF','French Southern Territories');
     insertCountry('GA','Gabon');
     insertCountry('GM','Gambia');
     insertCountry('GE','Georgia');
     insertCountry('DE','Germany');
     insertCountry('GH','Ghana');
     insertCountry('GI','Gibraltar');
     insertCountry('GR','Greece');
     insertCountry('GL','Greenland');
     insertCountry('GD','Grenada');
     insertCountry('GP','Guadeloupe');
     insertCountry('GU','Guam');
     insertCountry('GT','Guatemala');
     insertCountry('GG','Guernsey');
     insertCountry('GN','Guinea');
     insertCountry('GW','Guinea-Bissau');
     insertCountry('GY','Guyana');
     insertCountry('HT','Haiti');
     insertCountry('HM','Heard Island_and McDonald Islands');
     insertCountry('VA','Holy See (Vatican City State)');
     insertCountry('HN','Honduras');
     insertCountry('HK','Hong Kong');
     insertCountry('HU','Hungary');
     insertCountry('IS','Iceland');
     insertCountry('IN','India');
     insertCountry('ID','Indonesia');
     insertCountry('IR','Iran Islamic Republic ');
     insertCountry('IQ','Iraq');
     insertCountry('IE','Ireland');
     insertCountry('IM','Isle Man');
     insertCountry('IL','Israel');
     insertCountry('IT','Italy');
     insertCountry('JM','Jamaica');
     insertCountry('JP','Japan');
     insertCountry('JE','Jersey');
     insertCountry('JO','Jordan');
     insertCountry('KZ','Kazakhstan');
     insertCountry('KE','Kenya');
     insertCountry('KI','Kiribati');
     insertCountry('KP','Korea Democratic Peoples Republic');
     insertCountry('KR','Korea Republic');
     insertCountry('KW','Kuwait');
     insertCountry('KG','Kyrgyzstan');
     insertCountry('LA','Lao Peoples Democratic Republic');
     insertCountry('LV','Latvia');
     insertCountry('LB','Lebanon');
     insertCountry('LS','Lesotho');
     insertCountry('LR','Liberia');
     insertCountry('LY','Libya');
     insertCountry('LI','Liechtenstein');
     insertCountry('LT','Lithuania');
     insertCountry('LU','Luxembourg');
     insertCountry('MO','Macao');
     insertCountry('MK','Macedonia former Yugoslav Republic');
     insertCountry('MG','Madagascar');
     insertCountry('MW','Malawi');
     insertCountry('MY','Malaysia');
     insertCountry('MV','Maldives');
     insertCountry('ML','Mali');
     insertCountry('MT','Malta');
     insertCountry('MH','Marshall Islands');
     insertCountry('MQ','Martinique');
     insertCountry('MR','Mauritania');
     insertCountry('MU','Mauritius');
     insertCountry('YT','Mayotte');
     insertCountry('MX','Mexico');
     insertCountry('FM','Micronesia Federated States');
     insertCountry('MD','Moldova Republic');
     insertCountry('MC','Monaco');
     insertCountry('MN','Mongolia');
     insertCountry('ME','Montenegro');
     insertCountry('MS','Montserrat');
     insertCountry('MA','Morocco');
     insertCountry('MZ','Mozambique');
     insertCountry('MM','Myanmar');
     insertCountry('NA','Namibia');
     insertCountry('NR','Nauru');
     insertCountry('NP','Nepal');
     insertCountry('NL','Netherlands');
     insertCountry('NC','New_Caledonia');
     insertCountry('NZ','New_Zealand');
     insertCountry('NI','Nicaragua');
     insertCountry('NE','Niger');
     insertCountry('NG','Nigeria');
     insertCountry('NU','Niue');
     insertCountry('NF','Norfolk Island');
     insertCountry('MP','Northern Mariana Islands');
     insertCountry('NO','Norway');
     insertCountry('OM','Oman');
     insertCountry('PK','Pakistan');
     insertCountry('PW','Palau');
     insertCountry('PS','Palestinian Territory, Occupied');
     insertCountry('PA','Panama');
     insertCountry('PG','Papua Nueva Guinea');
     insertCountry('PY','Paraguay');
     insertCountry('PE','Peru');
     insertCountry('PH','Philippines');
     insertCountry('PN','Pitcairn');
     insertCountry('PL','Poland');
     insertCountry('PT','Portugal');
     insertCountry('PR','Puerto Rico');
     insertCountry('QA','Qatar');
     insertCountry('RE','Réunion');
     insertCountry('RO','Romania');
     insertCountry('RU','Russian Federation');
     insertCountry('RW','Rwanda');
     insertCountry('BL','Saint Barthélemy');
     insertCountry('SH','Saint Helena, Ascension_and Tristan da Cunha');
     insertCountry('KN','Saint Kitts_and Nevis');
     insertCountry('LC','Saint Lucia');
     insertCountry('MF','Saint Martin (French part)');
     insertCountry('PM','Saint Pierre_and Miquelon');
     insertCountry('VC','Saint Vincent_and_the Grenadines');
     insertCountry('WS','Samoa');
     insertCountry('SM','San Marino');
     insertCountry('ST','Sao Tome_and Principe');
     insertCountry('SA','Saudi Arabia');
     insertCountry('SN','Senegal');
     insertCountry('RS','Serbia');
     insertCountry('SC','Seychelles');
     insertCountry('SL','Sierra Leone');
     insertCountry('SG','Singapore');
     insertCountry('SX','Sint Maarten (Dutch part)');
     insertCountry('SK','Slovakia');
     insertCountry('SI','Slovenia');
     insertCountry('SB','Solomon Islands');
     insertCountry('SO','Somalia');
     insertCountry('ZA','South Africa');
     insertCountry('GS','South Georgia_and the_South Sandwich Islands');
     insertCountry('SS','South Sudan');
     insertCountry('ES','Spain');
     insertCountry('LK','Sri Lanka');
     insertCountry('SD','Sudan');
     insertCountry('SR','Suriname');
     insertCountry('SJ','Svalbard_and Jan Mayen');
     insertCountry('SZ','Swaziland');
     insertCountry('SE','Sweden');
     insertCountry('CH','Switzerland');
     insertCountry('SY','Syrian Arab Republic');
     insertCountry('TW','Taiwan, Province_of China');
     insertCountry('TJ','Tajikistan');
     insertCountry('TZ','Tanzania, United Republic_of');
     insertCountry('TH','Thailand');
     insertCountry('TL','Timor-Leste');
     insertCountry('TG','Togo');
     insertCountry('TK','Tokelau');
     insertCountry('TO','Tonga');
     insertCountry('TT','Trinidad_and Tobago');
     insertCountry('TN','Tunisia');
     insertCountry('TR','Turkey');
     insertCountry('TM','Turkmenistan');
     insertCountry('TC','Turks_and Caicos Islands');
     insertCountry('TV','Tuvalu');
     insertCountry('UG','Uganda');
     insertCountry('UA','Ukraine');
     insertCountry('AE','United Arab Emirates');
     insertCountry('GB','United Kingdom');
     insertCountry('US','United States');
     insertCountry('UM','United States Minor Outlying Islands');
     insertCountry('UY','Uruguay');
     insertCountry('UZ','Uzbekistan');
     insertCountry('VU','Vanuatu');
     insertCountry('VE','Venezuela Bolivarian Republic_of');
     insertCountry('VN','Viet Nam');
     insertCountry('VG','Virgin Islands, British');
     insertCountry('VI','Virgin Islands, U.S.');
     insertCountry('WF','Wallis_and Futuna');
     insertCountry('EH','Western Sahara');
     insertCountry('YE','Yemen');
     insertCountry('ZM','Zambia');
     insertCountry('ZW','Zimbabwe');
                

end;
0
0
