PL/SQL Developer Test script 3.0
180
-- Created on 24/09/2015 by ADMINISTRADOR 
declare 
  -- Local variables here
  i integer;
begin
  -- Test statements here
  inserts.person(6,
                 'Mario',
                 'Gonzalez',
                 'Rivera',
                 to_date('25/08/1967','DD/MM/YYYY'),
                 sysdate,
                 'Macho',
                 '300 east of church',
                 'Like to read',
                 'SAn Luis Gonzaga',
                 'UCR',
                 'Hospital Mexico',
                 20000,
                 1.6,
                 0,
                 4,
                 1,
                 1,
                 5,
                 2,
                 2,
                 5,
                 4,
                 18,
                 9,
                 7,
                 2,
                 1,
                 5,
                 273,
                 0,
                 0,
                 1);

inserts.person(7,
                 'Ana',
                 'Gómez',
                 'Gómez',
                 to_date('13/05/1975','DD/MM/YYYY'),
                 sysdate,
                 'Anita',
                 '200m north of MegaSuper',
                 'Like to cook',
                 'San Luis Gonzaga',
                 'UNA',
                 'AmbosMares',
                 5000,
                 1.57,
                 0,
                 0,
                 0,
                 1,
                 5,
                 3,
                 2,
                 5,
                 4,
                 19,
                 9,
                 5,
                 2,
                 2,
                 3,
                 272,
                 0,
                 0,
                 1);


inserts.person(8,
                 'Mariana',
                 'Lopezz',
                 'Castro',
                 to_date('2/04/1987','DD/MM/YYYY'),
                 sysdate,
                 'Nana',
                 '200m west of hospital',
                 'Like to dance',
                 'COVAO',
                 'UCR',
                 'ICE',
                 4000,
                 1.55,
                 0,
                 1,
                 1,
                 1,
                 3,
                 3,
                 2,
                 2,
                 4,
                 15,
                 9,
                 5,
                 2,
                 2,
                 3,
                 210,
                 0,
                 0,
                 0);
                 

inserts.person(9,
                 'Natalia',
                 'Venegas',
                 'Arce',
                 to_date('29/11/1995','DD/MM/YYYY'),
                 sysdate,
                 'Naty',
                 '200m north of school',
                 'Like to dance',
                 'Figueres Ferrer',
                 'UCR',
                 'HP',
                 10000,
                 1.62,
                 0,
                 0,
                 0,
                 1,
                 8,
                 3,
                 2,
                 2,
                 4,
                 12,
                 5,
                 4,
                 2,
                 1,
                 5,
                 120,
                 0,
                 0,
                 1);
                 

inserts.person(10,
                 'Josue',
                 'Martinez',
                 'Coto',
                 to_date('07/06/1979','DD/MM/YYYY'),
                 sysdate,
                 'Josu',
                 '200m north of restaurant',
                 'Like swin',
                 'Serafico',
                 'ITCR',
                 'ITCR',
                 15000,
                 1.9,
                 1,
                 2,
                 1,
                 1,
                 3,
                 2,
                 2,
                 2,
                 4,
                 10,
                 9,
                 8,
                 2,
                 2,
                 3,
                 272,
                 0,
                 0,
                 1);
                 
end;
0
0
